spring.application.name=demo-project
server.port=8080

# API key for open AI
spring.ai.openai.api-key=${OPENAI_API_KEY}

# ollama configs
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=codellama:latest
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.openai.enabled=false